Repository reflex-frp/reflex-dom, pull requests merged in 2019-01, with the labels that each got.

#284 reflex-dom: Add install-includes to .cabal
  reflex-dom/reflex-dom.cabal
Labels: bug fix

#282 Add INLINABLE to text, remove ChildResult
  reflex-dom-core/src/Reflex/Dom/Widget/Basic.hs
Labels: opinionated

#285 remove Reflex.Dom.Modals.Base until after RequesterT simplification
  reflex-dom-core/reflex-dom-core.cabal
  reflex-dom-core/src/Reflex/Dom/Core.hs
  reflex-dom-core/src/Reflex/Dom/Modals/Base.hs
Labels: clean up
